# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "BepInteraction",
    "InitialStateInteraction",
    "MEMKMBuilder",
    "Reaction",
    "TileSettings",
    "decode_state",
    "encode_state",
    "state_counts",
]

@typing.final
class BepInteraction:
    r"""
    Brønsted-Evans-Polanyi (proximity factor ω): the TS energy interpolates
    linearly between initial and final state, so only the ω-weighted change
    in interaction energy enters the barrier:
        correction = exp( -ω · (S_in - S_out) / kBT )
    ω = 0 is an early TS (rate blind to interactions), ω = 1 a late TS
    (barrier tracks the full reaction-energy shift). ω is independent kinetic
    information. A forward/reverse reaction pair satisfies detailed balance
    when their omegas sum to 1.
    """
    @property
    def epsilon(self) -> builtins.list[builtins.list[builtins.float]]: ...
    @property
    def omega(self) -> builtins.float: ...
    @property
    def kbt(self) -> builtins.float: ...
    def __new__(cls, epsilon: typing.Sequence[typing.Sequence[builtins.float]], omega: builtins.float, kbt: builtins.float = 1.0) -> BepInteraction: ...
    def with_omega(self, omega: builtins.float) -> BepInteraction:
        r"""
        Copy at a different ω; energies and kBT unchanged.
        """
    def site_energy_row(self, sp_in: builtins.int, sp_out: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Per-neighbor energy row for a reacting site sp_in -> sp_out. Exposed for
        the tensor-train backend; see the trait method.
        """
    def pair_energy(self, in0: builtins.int, out0: builtins.int, in1: builtins.int, out1: builtins.int) -> builtins.float:
        r"""
        Reacting pair's mutual-bond energy. Exposed for the tensor-train backend.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class InitialStateInteraction:
    r"""
    Initial-state approximation: the transition state carries no lateral
    interactions ("pinned" at the interaction-free reference), so the full
    initial-state (de)stabilisation enters the barrier:
        correction = exp( -S_in / kBT )
    Needs energies only — this scheme has no free kinetic parameter — and
    satisfies detailed balance by construction (forward and reverse share the
    pinned TS). It is its own scheme, not a special BEP ω: no single ω
    reproduces it for e.g. a hop.
    """
    @property
    def epsilon(self) -> builtins.list[builtins.list[builtins.float]]: ...
    @property
    def kbt(self) -> builtins.float: ...
    def __new__(cls, epsilon: typing.Sequence[typing.Sequence[builtins.float]], kbt: builtins.float = 1.0) -> InitialStateInteraction: ...
    @staticmethod
    def noninteracting(n_species: builtins.int, kbt: builtins.float = 1.0) -> InitialStateInteraction: ...
    def to_bep(self, omega: builtins.float) -> BepInteraction:
        r"""
        BEP model with the same energies at the given ω.
        """
    def site_energy_row(self, sp_in: builtins.int, sp_out: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Per-neighbor energy row for a reacting site sp_in -> sp_out (initial
        state carries the full interaction, so sp_out is unused). Exposed for
        the tensor-train backend; see the trait method.
        """
    def pair_energy(self, in0: builtins.int, out0: builtins.int, in1: builtins.int, out1: builtins.int) -> builtins.float:
        r"""
        Reacting pair's mutual-bond energy. Exposed for the tensor-train backend.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class MEMKMBuilder:
    r"""
    ME-MKM transition matrix builder.
    
    Tile geometry and reactions for ME-MKM.
    
    tile_settings defines the ring length and which site-offset pairs are
    neighbors (see TileSettings).
    
    species_names names every species; a reaction's integer codes index into it
    (0 = species_names[0], the conventional default "*"). It is the single source
    of truth for both the names and the species count: `n_species == len(species_names)`
    and the state space is `n_species ** l`. NOTE: n_species counts ALL species,
    index 0 included there is no implicit extra "empty" to add.
    An interaction model's epsilon is indexed in species_names order.
    
    Each Reaction can carry its own interaction model for its λ correction.
    If a Reaction has none, the builder's global model is used
    (default: noninteracting → all corrections = 1).
    """
    @property
    def tile_settings(self) -> TileSettings: ...
    @property
    def species_names(self) -> builtins.list[builtins.str]: ...
    @property
    def n_states(self) -> builtins.int: ...
    @property
    def n_pairs(self) -> builtins.int: ...
    @property
    def l(self) -> builtins.int:
        r"""
        Ring length (number of sites), from the tile settings.
        """
    @property
    def n_species(self) -> builtins.int:
        r"""
        Number of species. This counts any empty site as a
        specie which in the papers this is not the case.
        Its a practicality and generalization.
        """
    @property
    def n_rxns(self) -> builtins.int: ...
    def __new__(cls, tile_settings: TileSettings, reactions: typing.Sequence[Reaction], species_names: typing.Sequence[builtins.str], interaction: typing.Optional[InitialStateInteraction | BepInteraction] = None) -> MEMKMBuilder: ...
    def add_reaction(self, rxn: Reaction) -> None: ...
    def set_reactions(self, reactions: typing.Sequence[Reaction]) -> None: ...
    def get_reactions(self) -> builtins.list[Reaction]: ...
    def clear_reactions(self) -> None: ...
    def set_interaction(self, interaction: InitialStateInteraction | BepInteraction) -> None: ...
    def get_interaction(self) -> InitialStateInteraction | BepInteraction: ...
    def neighbor_pairs(self) -> builtins.list[tuple[builtins.int, builtins.int]]:
        r"""
        Undirected neighbor pairs (i < j), one entry per bond — the same
        geometry the W builder uses, exposed so Python doesn't re-derive it.
        """
    def coverage_classes(self) -> builtins.list[tuple[builtins.list[builtins.int], builtins.list[builtins.int]]]:
        r"""
        Partition every microstate by its coverage signature, returning one
        `(counts, indices)` entry per occupied class, sorted by `counts`.
        `counts[j]` is the number of sites carrying species `j + 1`; species 0's
        count is dropped from the key (it is fixed at `l - sum(counts)`, so it
        carries no extra information). This is the partition the graph viewer
        groups nodes by.
        """
    def select_states(self, min_counts: typing.Sequence[builtins.int], max_counts: typing.Sequence[builtins.int]) -> builtins.list[builtins.int]:
        r"""
        Microstate indices whose per-species site counts lie within the given
        inclusive bounds; `min_counts[s]`/`max_counts[s]` bound species `s` and
        both have length `n_species` (index 0 included -- no species is special).
        Fast path behind coverage-window queries (e.g. "coverage of A ≤ 0.2" →
        `max_counts[A] = ⌊0.2·l⌋`): one walk over the state space in Rust,
        returning only the matches.
        """
    def count_reactive(self, state: typing.Sequence[builtins.int], pattern_in: typing.Sequence[builtins.int]) -> builtins.int:
        r"""
        Reactive matches for `pattern_in` in a decoded microstate: sites equal
        to `pattern_in[0]` for an order-1 pattern, or ordered neighbor-pair
        matches for an order-2 pattern (each bond checked both ways, as the W
        builder does). Equals `-component.diagonal()` at unit rate; the graph
        exporter uses it as an edge multiplier.
        """
    def get_all_microstates(self) -> builtins.list[builtins.list[builtins.int]]: ...
    def build_w_coo(self) -> tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.list[builtins.float]]:
        r"""
        Full dynamical-form W as COO triples (rows, cols, vals); hand these
        straight to scipy.sparse on the Python side.
        """
    def build_w_components_coo(self) -> builtins.list[tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.list[builtins.float]]]:
        r"""
        One dynamical-form W matrix per reaction, each built at rate=1.
        
        W is linear in each reaction's rate constant, so for time-dependent
        rates k_i(t):  W(t) = Σ k_i(t) · components[i]. Useful for forced
        oscillations / Floquet-type driving, where rebuilding the full W from
        scratch at every ODE step would be wasteful.
        """
    def build_dw_dbeta_components_coo(self) -> builtins.list[tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.list[builtins.float]]]:
        r"""
        ∂(dynamical-form W)/∂β per reaction, each at unit base rate (β = 1/kbt).
        
        Mirrors build_w_components_coo's COO convention exactly, so Python can
        recombine both the same way: W = Σ k_i·components[i],
        ∂W/∂β = Σ k_i·dbeta_components[i] (rates are β-independent themselves;
        only the interaction correction factor depends on β).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Reaction:
    r"""
    A local reaction rule: pattern_in → pattern_out at base rate `rate`.
    
    pattern_in   : species codes of reacting sites (length 1 or 2)
    pattern_out  : species codes after reaction     (same length)
    rate         : base rate constant (before interaction correction)
    name         : human-readable label (e.g. "Adsorption of A")
    rate_symbol  : Simpl string symbol for the rate constant
                   used as the label above the arrow in the graph viewer.
                   Defaults to name if empty.
    rate_symbol_latex : Optional LaTeX string for the rate constant symbol (e.g. r"k_{\mathrm{ads}}")
    interaction  : optional per-reaction interaction model (any of the
                   InteractionModel implementors, e.g. InitialStateInteraction
                   or BepInteraction); if None the builder's global model
                   (default noninteracting) is used.
    """
    @property
    def pattern_in(self) -> builtins.list[builtins.int]: ...
    @pattern_in.setter
    def pattern_in(self, value: typing.Sequence[builtins.int]) -> None: ...
    @property
    def pattern_out(self) -> builtins.list[builtins.int]: ...
    @pattern_out.setter
    def pattern_out(self, value: typing.Sequence[builtins.int]) -> None: ...
    @property
    def rate(self) -> builtins.float: ...
    @rate.setter
    def rate(self, value: builtins.float) -> None: ...
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None: ...
    @property
    def rate_symbol(self) -> builtins.str: ...
    @rate_symbol.setter
    def rate_symbol(self, value: builtins.str) -> None: ...
    @property
    def rate_symbol_latex(self) -> typing.Optional[builtins.str]: ...
    @rate_symbol_latex.setter
    def rate_symbol_latex(self, value: typing.Optional[builtins.str]) -> None: ...
    def __new__(cls, pattern_in: typing.Sequence[builtins.int], pattern_out: typing.Sequence[builtins.int], rate: builtins.float, name: builtins.str = '', rate_symbol: builtins.str = '', rate_symbol_latex: typing.Optional[builtins.str] = None, interaction: typing.Optional[InitialStateInteraction | BepInteraction] = None) -> Reaction: ...
    def get_interaction(self) -> typing.Optional[InitialStateInteraction | BepInteraction]:
        r"""
        Get the per-reaction interaction model (None if not set: the builder's
        global model applies).
        """
    def set_interaction(self, interaction: typing.Optional[InitialStateInteraction | BepInteraction]) -> None:
        r"""
        Set a per-reaction interaction model.
        """
    def with_rate(self, rate: builtins.float) -> Reaction: ...
    def with_rate_symbol(self, rate_symbol: builtins.str) -> Reaction: ...
    def with_interaction(self, interaction: typing.Optional[InitialStateInteraction | BepInteraction]) -> Reaction: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TileSettings:
    r"""
    Bond set defining which site-offset pairs are neighbors.
    
    For a ring of l sites, two sites i and j are neighbors if
    (i - j) % l ∈ deltas or (j - i) % l ∈ deltas.
    """
    @property
    def sites(self) -> builtins.int: ...
    @property
    def deltas(self) -> builtins.list[builtins.int]: ...
    def __new__(cls, sites: builtins.int, deltas: typing.Sequence[builtins.int]) -> TileSettings:
        r"""
        Here deltas are the site offsets that define neighbors.
        For a ring of l sites, two sites i and j are neighbors
        if (i - j) % l ∈ deltas or (j - i) % l ∈ deltas.
        """
    @staticmethod
    def greek_cross() -> TileSettings:
        r"""
        Corresponds to the greek cross tiles
        """
    @staticmethod
    def square(sites: builtins.int, d: builtins.int) -> TileSettings:
        r"""
        Corresponds to the brickwork tiles
        """
    @staticmethod
    def hex(d: builtins.int) -> TileSettings:
        r"""
        Corresponds to the hexagonal "creamcups" tile: 7 sites (six around one
        centre), a complete K_7 under deltas [1, d, d+1].
        """
    @staticmethod
    def custom(sites: builtins.int, deltas: typing.Sequence[builtins.int]) -> TileSettings: ...
    @staticmethod
    def validate_square(l: builtins.int, d: builtins.int) -> tuple[builtins.bool, builtins.bool, builtins.bool]:
        r"""
        Validate primary (l,d) brickwork pair against Adams et al. 2025 SI Figure S3.
        
        This is purely a geometric sanity check on the (ring length, offset)
        pair, independent of whatever reactions get attached later:
        - rule1: d=0 or d=l would make a site its own periodic neighbor.
        - rule2: a valid square-lattice fold needs l even and d odd, so
          stepping by d always flips parity.
        - checkerboard: whether this (l, d) can additionally host a strict
          alternating 2-coloring. This is stricter than rule2: d=1 is just
          the brickwork's nearest-neighbor offset and adds no new bond
          type, d=l-1 is d=1 read the other way around the ring, and
          d=l/2 (even l) is its own mirror image (i+d and i-d land on the
          same site). All three are valid square-lattice tiles (rule1 and
          rule2 pass) but cannot represent the checkerboard superlattice.
        """
    @staticmethod
    def smallest_valid_square(sites: builtins.int, checkerboard: builtins.bool) -> typing.Optional[TileSettings]:
        r"""
        Smallest brickwork offset d (searched from d=1 up) for a ring of
        `sites` sites that is fully valid per Tile::validate: rule1, rule2,
        AND checkerboard-capable (Adams et al. 2025 SI Figure S3) if requested.
        Returns None if no such d exists for this l (e.g. sites odd, or sites=4).
        """
    def l(self) -> builtins.int:
        r"""
        The number of sites in the tile (ring length). Same as sites.
        """
    def d(self) -> builtins.int:
        r"""
        The primary long-range offset (largest delta), used for Adams 2025 validation.
        """
    def __repr__(self) -> builtins.str: ...

def decode_state(idx: builtins.int, l: builtins.int, base: builtins.int) -> builtins.list[builtins.int]:
    r"""
    Decode a microstate index into its site vector.
    
    A tile microstate is a length-`l` vector with one entry per site, each in
    `[0, base)` where `base` = n_species (species 0 is conventionally the
    vacant/reference site). `idx` is that vector read as a base-`base`
    positional integer with `site[0]` as the most significant digit and
    `site[l-1]` as the least significant, i.e.
    `idx = sum(site[i] * base^(l-1-i) for i in 0..l)`. This is the
    base-(m+1) enumeration used in the paper to index all `base^l`
    microstates as `idx in 0..n_states`. `l` and `base` are tile parameters
    you must supply; they aren't recoverable from `idx` alone.
    """

def encode_state(tile_microstate: typing.Sequence[builtins.int], base: builtins.int) -> builtins.int:
    r"""
    Encode a microstate site vector into its index (inverse of `decode_state`).
    
    `tile_microstate` is the length-`l` vector of per-site species in
    `[0, base)`; see `decode_state` for the digit-order convention.
    """

def state_counts(idx: builtins.int, l: builtins.int, base: builtins.int) -> builtins.list[builtins.int]: ...

