# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "InteractionModel",
    "MEMKMBuilder",
    "Reaction",
    "TileSettings",
    "decode_state",
    "encode_state",
    "state_counts",
]

@typing.final
class InteractionModel:
    r"""
    Pairwise nearest-neighbor interaction energies ε[s1][s2].
    
    Rate correction for a reaction event:
        correction = exp( -Sum_{non-reacting neighbors} ε[sp_reacting][sp_neighbor] / kBT )
    
    The sum runs over non-reacting neighbors of each reacting site.
    """
    @property
    def epsilon(self) -> builtins.list[builtins.list[builtins.float]]: ...
    @property
    def kbt(self) -> builtins.float: ...
    def __new__(cls, epsilon: typing.Sequence[typing.Sequence[builtins.float]], kbt: builtins.float = 1.0) -> InteractionModel: ...
    @staticmethod
    def noninteracting(n_species: builtins.int, kbt: builtins.float) -> InteractionModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class MEMKMBuilder:
    r"""
    ME-MKM transition matrix builder.
    
    Tile geometry and reactions for ME-MKM.
    
    tile_settings defines the ring length and which site-offset pairs are
    neighbors (see TileSettings).
    
    species_names names every species; a reaction's integer codes index into it
    (0 = species_names[0], the conventional default "*"). It is the single source
    of truth for both the names and the species count: `n_species == len(species_names)`
    and the state space is `n_species ** l`. NOTE: n_species counts ALL species,
    index 0 included -- there is no implicit extra "empty" to add.
    InteractionModel.epsilon is indexed in species_names order.
    
    Each Reaction can carry its own InteractionModel for its λ correction.
    If a Reaction has none, the builder's global InteractionModel is used
    (default: noninteracting → all corrections = 1).
    """
    @property
    def tile_settings(self) -> TileSettings: ...
    @property
    def species_names(self) -> builtins.list[builtins.str]: ...
    @property
    def n_states(self) -> builtins.int: ...
    @property
    def n_pairs(self) -> builtins.int: ...
    @property
    def l(self) -> builtins.int:
        r"""
        Ring length (number of sites), from the tile settings.
        """
    @property
    def n_species(self) -> builtins.int:
        r"""
        Number of species, counting index 0. Equals the state-space base, so the
        microstate count is n_species ** l. (There is no separate empty species
        to add: index 0 is already one of the n_species.)
        """
    @property
    def d(self) -> builtins.int:
        r"""
        Primary long-range offset; largest delta in the tile settings.
        Kept for convenience and Adams 2025 validate().
        """
    @property
    def n_rxns(self) -> builtins.int: ...
    def __new__(cls, tile_settings: TileSettings, reactions: typing.Sequence[Reaction], species_names: typing.Sequence[builtins.str], interaction: typing.Optional[InteractionModel] = None) -> MEMKMBuilder: ...
    def add_reaction(self, rxn: Reaction) -> None: ...
    def set_reactions(self, reactions: typing.Sequence[Reaction]) -> None: ...
    def get_reactions(self) -> builtins.list[Reaction]: ...
    def clear_reactions(self) -> None: ...
    def set_interaction(self, interaction: InteractionModel) -> None: ...
    def get_interaction(self) -> InteractionModel: ...
    def validate(self) -> dict: ...
    def neighbor_pairs(self) -> builtins.list[tuple[builtins.int, builtins.int]]:
        r"""
        Undirected neighbor pairs (i < j), one entry per bond — the same
        geometry the W builder uses, exposed so Python doesn't re-derive it.
        """
    def coverage_classes(self) -> builtins.list[tuple[builtins.list[builtins.int], builtins.list[builtins.int]]]:
        r"""
        Partition every microstate by its coverage signature, returning one
        `(counts, indices)` entry per occupied class, sorted by `counts`.
        `counts[j]` is the number of sites carrying species `j + 1`; species 0's
        count is dropped from the key (it is fixed at `l - sum(counts)`, so it
        carries no extra information). This is the partition the graph viewer
        groups nodes by.
        """
    def select_states(self, min_counts: typing.Sequence[builtins.int], max_counts: typing.Sequence[builtins.int]) -> builtins.list[builtins.int]:
        r"""
        Microstate indices whose per-species site counts lie within the given
        inclusive bounds; `min_counts[s]`/`max_counts[s]` bound species `s` and
        both have length `n_species` (index 0 included -- no species is special).
        Fast path behind coverage-window queries (e.g. "coverage of A ≤ 0.2" →
        `max_counts[A] = ⌊0.2·l⌋`): one walk over the state space in Rust,
        returning only the matches.
        """
    def count_reactive(self, state: typing.Sequence[builtins.int], pattern_in: typing.Sequence[builtins.int]) -> builtins.int:
        r"""
        Reactive matches for `pattern_in` in a decoded microstate: sites equal
        to `pattern_in[0]` for an order-1 pattern, or ordered neighbor-pair
        matches for an order-2 pattern (each bond checked both ways, as the W
        builder does). Equals `-component.diagonal()` at unit rate; the graph
        exporter uses it as an edge multiplier.
        """
    def build_w_coo(self) -> tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.list[builtins.float]]:
        r"""
        Full dynamical-form W as COO triples (rows, cols, vals); hand these
        straight to scipy.sparse on the Python side.
        """
    def build_w_ss_coo(self) -> tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.list[builtins.float]]:
        r"""
        Same as build_w_coo, but with the last row swapped for the
        normalisation condition (all 1s) so it's ready to solve for the
        steady-state distribution directly.
        """
    def build_w_components_coo(self) -> builtins.list[tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.list[builtins.float]]]:
        r"""
        One dynamical-form W matrix per reaction, each built at rate=1.
        
        W is linear in each reaction's rate constant, so for time-dependent
        rates k_i(t):  W(t) = Σ k_i(t) · components[i]. Useful for forced
        oscillations / Floquet-type driving, where rebuilding the full W from
        scratch at every ODE step would be wasteful.
        """
    def build_dw_dbeta_components_coo(self) -> builtins.list[tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.list[builtins.float]]]:
        r"""
        ∂(dynamical-form W)/∂β per reaction, each at unit base rate (β = 1/kbt).
        
        Mirrors build_w_components_coo's COO convention exactly, so Python can
        recombine both the same way: W = Σ k_i·components[i],
        ∂W/∂β = Σ k_i·dbeta_components[i] (rates are β-independent themselves;
        only the interaction correction factor depends on β).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Reaction:
    r"""
    A local reaction rule: pattern_in → pattern_out at base rate `rate`.
    
    pattern_in   : species codes of reacting sites (length 1 or 2)
    pattern_out  : species codes after reaction     (same length)
    rate         : base rate constant (before interaction correction)
    name         : human-readable label (e.g. "Adsorption of A")
    rate_symbol  : Simpl string symbol for the rate constant
                   used as the label above the arrow in the graph viewer.
                   Defaults to name if empty.
    rate_symbol_latex : Optional LaTeX string for the rate constant symbol (e.g. r"k_{\mathrm{ads}}")
    interaction  : optional per-reaction InteractionModel; if None the builder's
                   global InteractionModel (default noninteracting) is used.
    """
    @property
    def pattern_in(self) -> builtins.list[builtins.int]: ...
    @pattern_in.setter
    def pattern_in(self, value: typing.Sequence[builtins.int]) -> None: ...
    @property
    def pattern_out(self) -> builtins.list[builtins.int]: ...
    @pattern_out.setter
    def pattern_out(self, value: typing.Sequence[builtins.int]) -> None: ...
    @property
    def rate(self) -> builtins.float: ...
    @rate.setter
    def rate(self, value: builtins.float) -> None: ...
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None: ...
    @property
    def rate_symbol(self) -> builtins.str: ...
    @rate_symbol.setter
    def rate_symbol(self, value: builtins.str) -> None: ...
    @property
    def rate_symbol_latex(self) -> typing.Optional[builtins.str]: ...
    @rate_symbol_latex.setter
    def rate_symbol_latex(self, value: typing.Optional[builtins.str]) -> None: ...
    def __new__(cls, pattern_in: typing.Sequence[builtins.int], pattern_out: typing.Sequence[builtins.int], rate: builtins.float, name: builtins.str = '', rate_symbol: builtins.str = '', rate_symbol_latex: typing.Optional[builtins.str] = None, interaction: typing.Optional[InteractionModel] = None) -> Reaction: ...
    def get_interaction(self) -> typing.Optional[InteractionModel]:
        r"""
        Get the per-reaction InteractionModel (None if not including interactions (builder default)).
        """
    def set_interaction(self, interaction: typing.Optional[InteractionModel]) -> None:
        r"""
        Set a per-reaction InteractionModel.
        """
    def with_rate(self, rate: builtins.float) -> Reaction: ...
    def with_rate_symbol(self, rate_symbol: builtins.str) -> Reaction: ...
    def with_interaction(self, interaction: typing.Optional[InteractionModel]) -> Reaction: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TileSettings:
    r"""
    Bond set defining which site-offset pairs are neighbors.
    
    For a ring of l sites, two sites i and j are neighbors if
    (i - j) % l ∈ deltas or (j - i) % l ∈ deltas.
    """
    @property
    def sites(self) -> builtins.int: ...
    @property
    def deltas(self) -> builtins.list[builtins.int]: ...
    def __new__(cls, sites: builtins.int, deltas: typing.Sequence[builtins.int]) -> TileSettings:
        r"""
        Here deltas are the site offsets that define neighbors.
        For a ring of l sites, two sites i and j are neighbors
        if (i - j) % l ∈ deltas or (j - i) % l ∈ deltas.
        """
    @staticmethod
    def greek_cross() -> TileSettings:
        r"""
        Corresponds to the greek cross tiles
        """
    @staticmethod
    def square(sites: builtins.int, d: builtins.int) -> TileSettings:
        r"""
        Corresponds to the brickwork tiles
        """
    @staticmethod
    def hex(d: builtins.int) -> TileSettings:
        r"""
        Corresponds to the hexagonal "creamcups" tile: 7 sites (six around one
        centre), a complete K_7 under deltas [1, d, d+1].
        """
    @staticmethod
    def custom(sites: builtins.int, deltas: typing.Sequence[builtins.int]) -> TileSettings: ...
    def l(self) -> builtins.int:
        r"""
        The number of sites in the tile (ring length). Same as sites.
        """
    def d(self) -> builtins.int:
        r"""
        The primary long-range offset (largest delta), used for Adams 2025 validation.
        """
    def __repr__(self) -> builtins.str: ...

def decode_state(microstate: builtins.int, l: builtins.int, base: builtins.int) -> builtins.list[builtins.int]:
    r"""
    Given a state vector for a tile of `l` sites, you can encode it into a microstate "number" given the known base (number of species).
    """

def encode_state(microstate: typing.Sequence[builtins.int], base: builtins.int) -> builtins.int:
    r"""
    Given a microstate "number", you can decode it given the known base and tile length.
    Usually, you want to use the coverage_classes() or select_states() methods to get
    a list of microstates that match a coverage signature, rather than decoding every
    state yourself.
    """

def state_counts(idx: builtins.int, l: builtins.int, base: builtins.int) -> builtins.list[builtins.int]: ...

